language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.2
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
sudo: false
matrix:
  exclude:
    - rvm: 2.6.2
      gemfile: gemfiles/4.2.gemfile
